name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Type of Feature
      description: What type of feature are you proposing?
      options:
        - New Functionality
        - User Interface Enhancement
        - Performance Improvement
        - Documentation
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe what problem you're trying to solve.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see implemented?
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: What alternative solutions or features have you considered?
      placeholder: |
        A clear and concise description of any alternative solutions or features you've considered. For example:
        - Alternative 1: [...]
        - Alternative 2: [...]
        - Why these alternatives are not preferred: [...]

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: How would you categorize the impact of this feature?
      options:
        - High (Critical functionality)
        - Medium (Significant improvement)
        - Low (Nice to have)
    validations:
      required: true

  - type: textarea
    id: implementation-details
    attributes:
      label: Implementation Details
      description: If you have any ideas about how to implement this feature, please share them.
      placeholder: |
        Consider including:
        - Technical approach
        - Required changes
        - Potential challenges
        - Dependencies

  - type: checkboxes
    id: requirements
    attributes:
      label: Requirements
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that match this one
          required: true
        - label: I am willing to help implement this feature
        - label: This feature would benefit the broader community
          required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: You can drag and drop images here to include them.

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How can we measure the success of this feature?
      placeholder: |
        For example:
        - Specific metrics
        - User feedback
        - Performance improvements
